### ISSUE TITLE
`headerTransparent: false` in embedded stack adds white area at bottom of screen

### ISSUE THREAD

**Issue by johankasperi** [okwasniewski/react-native-bottom-tabs#161]
### Before submitting a new issue

- [X] I tested using the latest version of the library, as the bug might be already fixed.
- [X] I tested using a [supported version](https://github.com/reactwg/react-native-releases/blob/main/docs/support.md) of react native.
- [X] I checked for possible duplicate issues, with possible answers.

### Bug summary

When using `headerTransparent: false` and `headerLargeTitle: false` in an embedded native stack navigator a white area occurs at bottom of screen on iPad with iOS >= 18. The bug can be replicated in the example app when changing this line to `false` https://github.com/okwasniewski/react-native-bottom-tabs/blob/af0c62af8ab408a6b5e78622dca32b01b774aecc/apps/example/src/Examples/NativeBottomTabsEmbeddedStacks.tsx#L10

Printscreen of the bug:
![Simulator Screenshot - iPad Air 11-inch (M2) - 2024-11-25 at 16 15 13](https://github.com/user-attachments/assets/c783bfde-e363-48c6-8b74-b317601662ae)

Unsure if the issue is with this library or `react-native-screens` but posting it here since the bug does not occur with @react-navigation/bottom-tabs

### Library version

0.6.0

### Environment info

```shell
From the example app:

System:
  OS: macOS 14.7.1
  CPU: (10) arm64 Apple M1 Pro
  Memory: 297.39 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.17.0
    path: ~/.nvm/versions/node/v20.17.0/bin/node
  Yarn:
    version: 3.6.1
    path: ~/.nvm/versions/node/v20.17.0/bin/yarn
  npm:
    version: 10.8.2
    path: ~/.nvm/versions/node/v20.17.0/bin/npm
  Watchman:
    version: 2024.08.12.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /Users/johan.kasperi/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.1
      - iOS 18.1
      - macOS 15.1
      - tvOS 18.1
      - visionOS 2.1
      - watchOS 11.1
  Android SDK:
    API Levels:
      - "28"
      - "30"
      - "34"
      - "35"
    Build Tools:
      - 28.0.3
      - 29.0.2
      - 29.0.3
      - 30.0.2
      - 30.0.3
      - 31.0.0
      - 32.0.0
      - 33.0.0
      - 33.0.0
      - 33.0.1
      - 34.0.0
      - 34.0.0
      - 35.0.0
    System Images:
      - android-22 | Google APIs ARM 64 v8a
      - android-23 | Google APIs ARM 64 v8a
      - android-25 | Google APIs ARM 64 v8a
      - android-28 | Google ARM64-V8a Play ARM 64 v8a
      - android-35 | Google APIs ARM 64 v8a
      - android-VanillaIceCream | Google Play ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2024.2 AI-242.23339.11.2421.12483815
  Xcode:
    version: 16.1/16B40
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.5
    path: /Users/johan.kasperi/.sdkman/candidates/java/current/bin/javac
  Ruby:
    version: 2.7.5
    path: /Users/johan.kasperi/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: false
  newArchEnabled: false
iOS:
  hermesEnabled: false
  newArchEnabled: false
```

### Steps to reproduce

1. Change this line to `false` in the example app:  https://github.com/okwasniewski/react-native-bottom-tabs/blob/af0c62af8ab408a6b5e78622dca32b01b774aecc/apps/example/src/Examples/NativeBottomTabsEmbeddedStacks.tsx#L10
2. Run example app

### Reproducible sample code

```js
I think running the example app with the "steps to reproduce" is sufficient? Please let me know if I need to setup a runnable repro.
```

**Comment by okwasniewski** [comment]
Hey, thanks for opening the issue! 

Can you try setting `ignoresTopSafeArea={false}` on the navigator? It looks like it fixes the issue for me when running on iPad with this config of React Native Screens.

**Comment by Robert27** [comment]
Same issue here.
By setting `ignoresTopSafeArea={false}` the white area is kinda gone. But The iOS navigation bar still has the white background and is not translucent. 
<img width="543" alt="Screenshot 2024-11-27 at 20 06 45" src="https://github.com/user-attachments/assets/a80c7f82-3e23-450c-97ee-84a004596fe9">

**Comment by johankasperi** [comment]
> Same issue here. By setting `ignoresTopSafeArea={false}` the white area is kinda gone. But The iOS navigation bar still has the white background and is not translucent. <img alt="Screenshot 2024-11-27 at 20 06 45" width="543" src="https://private-user-images.githubusercontent.com/53063597/390537855-a80c7f82-3e23-450c-97ee-84a004596fe9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4MDAxNDIsIm5iZiI6MTczMjc5OTg0MiwicGF0aCI6Ii81MzA2MzU5Ny8zOTA1Mzc4NTUtYTgwYzdmODItM2UyMy00NTBjLTk3ZWUtODRhMDA0NTk2ZmU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDEzMTcyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0NjViNDZhYzQ2ZGVjNTNmMzUyMzU2ZWJhMDY4NTZlZDYzZDVlM2JhZThmYTY1MTdhYTdhZTE0OTM5YWZiNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uajc0MFz9vS3e2ZM0W3t7o434R8S8BO26bH_BEcg3Vw"> And on screens without a stack / header the statusbar becomes blank (no longer translucent).

Same thing happening for me

**Comment by okwasniewski** [comment]
Thanks for confirming! Looks like it makes it a bit better 👍🏻 I will check why it's still not under the bar

**Comment by okwasniewski** [comment]
Should be fixed in 0.7.2 without SafeAreaView

**Comment by johankasperi** [comment]
@okwasniewski this issue seems to still exist? Testing in 0.9.0 and when adding `headerTransparent: false` in the `headerOptions` in NativeBottomTabsEmbeddedStacks I'm seeing the same white space on ipadOS 18. In 0.9.0 `ignoresTopSafeAreaTop` is also removed so unable to get the "smaller" white space. Above you said it should be fixed "without SafeAreaView", what do you mean by that? Thank you!

![Image](https://github.com/user-attachments/assets/c3759b88-7a06-43a3-ba20-c47b5c5293c7)
