### ISSUE TITLE
SidebarAdaptable does not push screen content

### ISSUE THREAD

**Issue by Robert27** [okwasniewski/react-native-bottom-tabs#165]
### Before submitting a new issue

- [X] I tested using the latest version of the library, as the bug might be already fixed.
- [X] I tested using a [supported version](https://github.com/reactwg/react-native-releases/blob/main/docs/support.md) of react native.
- [X] I checked for possible duplicate issues, with possible answers.

### Bug summary

If I set `sidebarAdaptable` to true, then the sidebar superimposes the content of the screen, instead of it being pushed to the side and nothing is covered.
As a enduser I expect the sidebar not to overlay may app content.

### Library version

0.7.0

### Environment info

```shell
System:
  OS: macOS 15.1.1
  CPU: (10) arm64 Apple M1 Pro
  Memory: 260.08 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 23.3.0
    path: /opt/homebrew/bin/node
  Yarn:
    version: 4.0.1
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.9.0
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2024.11.18.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.16.2
    path: /Users/roberteggl/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.1
      - iOS 18.1
      - macOS 15.1
      - tvOS 18.1
      - visionOS 2.1
      - watchOS 11.1
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.2 AI-242.23339.11.2421.12483815
  Xcode:
    version: 16.1/16B40
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.1
    path: /usr/bin/javac
  Ruby:
    version: 3.2.2
    path: /Users/roberteggl/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 15.1.2
    wanted: latest
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.76.3
    wanted: 0.76.3
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Steps to reproduce

1. Use this lib with expo-router (see sample code)
2. Set `sidebarAdaptable` to true
3. Run the app on iPadOS.

![Simulator Screenshot - iPad Pro 11-inch (M4) - 2024-11-27 at 16 36 06](https://github.com/user-attachments/assets/3b5ddd12-d18b-4566-9129-3ef46d009085)

### Reproducible sample code

```js
Demo: https://github.com/Robert27/expo-router-react-native-bottom-tabs/tree/demo
```

**Comment by okwasniewski** [comment]
Hey, 

Thanks for opening the issue. 

Can you try using <SafeAreaView/>? 

This should make sure that your content is not overlapped by the sidebar

**Comment by Robert27** [comment]
It doesn't work. I tried it in many different ways, but using `SafeAreaView` does not fix the issue.

**Comment by Robert27** [comment]
I did some more tests and I was kinda wrong.
It works as excepted when using `SafeAreaView` from react native. I tried the one from `react-native-safe-area-view` before which does not have any effect.
Although components like `react-native-bottom-sheet` are still shown full screen, but I don't know if we can fix this.

![Simulator Screenshot - iPad Pro 11-inch (M4) - 2024-11-28 at 01 29 31](https://github.com/user-attachments/assets/594bacb0-e635-4b65-89a4-a319dce0c253)

**Comment by okwasniewski** [comment]
Thanks for double checking @Robert27, I'm thinking how we can resolve this... I'll investigate if resizing child views to the size of the available space is an option, that way we wouldn't need SafeAreaView. 

Weird that bottom sheet is still underneath, I wonder if the same would happen with the native sheet (https://github.com/lodev09/react-native-true-sheet) but we should definitely support JS sheet too. In theory if we resize the view the sheet would also be resized

**Comment by okwasniewski** [comment]
Hey, you can now remove SafeAreaView, it should be fixed in 0.7.2

**Comment by MrFunctor** [comment]
Hello @okwasniewski, this issue still happens on the latest version (`0.11.1`). The only fix is to use `SafeAreaView` from `react-native` as described above (the one from `react-native-safe-area-context` has no effect). Has there been a regression?

**Comment by liixing** [comment]
same issue
